### ISSUE TITLE
Question about "contains" assertion

### ISSUE THREAD

**Issue by jeratora** [quintush/helm-unittest#113]
Hi.

I'm trying to test the existence of an item of an array without using any positional value.

Yaml to be tested is :
```yaml
spec:
  scopes:
    - phony-service.phony:graphql 
 ```
Please note that `phony-service.phony:graphql` is not a key/value pair but a whole string.

The following assertion fails:
```yaml
    asserts:
    - contains:
        path: spec.scopes
        content:
          phony-service.phony:graphql
        count: 1
        any: true
```
with that odd error:
```yaml
                - asserts[0] `contains` fail
                        Template:       anything/templates/apiresource.yaml
                        DocumentIndex:  0
                        Path:   spec.scopes
                        Expected to contain:
                                - phony-service.phony:graphql
                        Actual:
                                - phony-service.phony:graphql
```

Whereas the "positional" assertation works:

```yaml
    asserts:
    - equal:
        path: spec.scopes[0]
        value: "phony-service.phony:graphql"
````

Any idea about what I could have missed ? Thanks in advance.

**Comment by jeratora** [comment]
Some additional info about that issue

If the yaml to be tested is:
```yaml
spec:
  scopes:
    - phony-service.phony:graphql
    - name: something
 ```
Then the error is:
```yaml
                - asserts[0] `contains` fail
                        Template:       standard-microservice/templates/apiresource.yaml
                        DocumentIndex:  0
                        Path:   spec.scopes
                        Expected to contain:
                                - phony-service.phony:graphql
                        Actual:
                                - phony-service.phony:graphql
                                - name: something
```

Shouldn't `any: true` prevent this ?
