### ISSUE TITLE
import-values of subcharts not applied in some cases

### ISSUE THREAD

**Issue by rquinio1A** [quintush/helm-unittest#115]
I'm trying to use helm-unittest 0.2.6 on Windows to test my charts, but I noticed something weird: 
- Everything works fine with the first 2 test cases
- But when I add a 3rd case (identical to the 2nd case, in the same test suite or a separate one), then import-values is not honored and I get nil errors on some global values.

My Chart.yaml has:

```yaml
dependencies:
  - name: library-chart
    import-values:
      - child: microservice
        parent: microservice
      - child: global
        parent: global
```

The difference I see in the vscode debugger is at:
https://github.com/helm/helm/blob/b1e24764325135b364a7f81fb0aab683d190c546/pkg/chartutil/dependencies.go#L234

* for the first 2 test cases , r.ImportValues is of type `<map[string]interface {}>`
![type-ok](https://user-images.githubusercontent.com/58322910/118991960-7c781c00-b984-11eb-9b3c-178ea3045874.png)

* for the 3rd test case, r.ImportValues is of type `<map[string]string>`, so it doesn't match any of the switch cases, and values are not imported !
 ![type-ko](https://user-images.githubusercontent.com/58322910/118991986-826dfd00-b984-11eb-98e9-d21775abc629.png)

I'm a newbie at Golang and not sure what the root cause may be...
But it's strange that chart object instances would be constructed differently, given it's the same Chart.yaml and test case config.
