### ISSUE TITLE
Question: Testing rendered ConfigMaps

### ISSUE THREAD

**Issue by JasonCrease** [quintush/helm-unittest#116]
We have some `ConfigMap`s with complicated data items for configuration files and such. Since these are strings, we end up doing a lot of `contains` and `matchRegex` to ensure things are within the file. But since the Strings are usually structured, we'd love to be able to do something like:

```
templates:
  - configmap.yaml
[...]
    asserts:
      - equal:
          path: data.big_config_file\.yaml
          location: storage.db.username[2]
          pattern: "john_smith"
```

i.e. Using JSONPath to locate items in Strings.

Is this a feature on the backlog? Or is there a workaround? Thanks!
