### ISSUE TITLE
How can you view the the rendored template, when a test fails

### ISSUE THREAD

**Issue by fieldju** [quintush/helm-unittest#149]
:wave: hello, new to using this library.

I have a test

```yaml
suite: rna tests
tempaltes:
  - deployment.yaml
tests:
  - it: adds env vars to the rna pod
    values:
      - values/env-var-values.yaml
    asserts:
      - equal:
          path: spec.template.spec.containers[0].env[0].name
          value: FOO
      - equal:
          path: spec.template.spec.containers[0].env[0].value
          value: bar
```

Its failing

```zsh
❯ helm unittest --helm3 .

### Chart [ remote-network-agent ] .

 FAIL  rna tests        tests/deployment_test.yaml
        - adds env vars to the rna pod

                - asserts[0] `equal` fail

                - asserts[1] `equal` fail


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        1.647489ms

Error: plugin "unittest" exited with error
```

I'd like to see what was rendored when a tests fails or just in general to help write the tests.

Is there a way to see the rednored templates that I am missing?
