### ISSUE TITLE
FR: `isSubset` assertion to handle multiple keys

### ISSUE THREAD

**Issue by iben12** [quintush/helm-unittest#162]
It would be a nice feature if `isSubset` could handle multiple keys, not just one.

What I mean? Take this manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    one: 1
    two: 2
    three: 3
...
```

For this I would like to assert that a _subset_ of the labels are present, but do not care about the rest:
```yaml
isSubset:
  path: metadata.labels
  content:
    one: 1
    three: 3
# this fails
```
I think this is in line what _subset_ means. The current implementation of `isSubset` is rather `hasElement`.

If I want to achieve the above now, I can either assert `isSubset` one-by-one for relevant labels, or `equal` to all labels including all irrelevant keys.

What do you think?
