### ISSUE TITLE
[bug] - contains fails when expected and actual content is the same

### ISSUE THREAD

**Issue by froy001** [quintush/helm-unittest#174]
The template:
```yaml
 volumes:
        - name: config-volume
          configMap:
            name: davf-app-02
        - name: all-vault
          projected:
            sources:
              - secret:
                  name: common-vault
        - configMap:
            name: foo-configMap-2
          name: foo-configmap-volume-2
        - name: foo-secret-volume-2
          secret:
            items:
            - key: foo-key-2
              path: foo-key.txt
            secretName: 'dev-foo-secret-2'
```

The test:
```yaml
      - contains:
          path: spec.template.spec.volumes[3].secret.items
          content:
            key: foo-key-2 
            path: foo-key.txt 
          count: 1
          any: true
```

The failure:

```yaml
- asserts[1] `contains` fail
     Template:	charts-integration-test/charts/app-02/templates/deployment.yaml
      DocumentIndex:	0
      Path:	spec.template.spec.volumes[3].secret.items
      Expected to contain:
	  - key: foo-key-2
	    path: foo-key.txt
       Actual:
	  - key: foo-key-2
	    path: foo-key.txt
````
Obviously this should pass.

**Comment by quintush** [comment]
Hello @froy001,

I would agree, however I have seen this behavior earlier.
I will try to reproduce this issue.

Greetings,
@quintush

**Comment by cristiadu** [comment]
PS:  I could use `equals` on `spec.servers[0]` with the whole YAML structure, so that can be a workaround if you know for sure the array index to match.

**Comment by froy001** [comment]
@cristiadu Following up on your suggestion:

The template:
```yaml
volumes:
        - name: config-volume
          configMap:
            name: app-02
        - name: all-vault
          projected:
            sources:
              - secret:
                  name: common-vault
```

The test (expecting 'false' logic to not render a volume):
```yaml
  - it: should not render the rookout volume when rookout.enabled is not given
    templates:
      - charts/app-01/templates/deployment.yaml
      - charts/app-02/templates/deployment.yaml
    asserts:
      - isNull:
          path: spec.template.spec.volumes[2]
```

test result:
```yaml
	- should not render the rookout volume when rookout.enabled is not given

		- asserts[0] `isNull` fail
			Template:	charts-integration-test/charts/app-01/templates/deployment.yaml
			DocumentIndex:	0
			Error:
				[2] :
				- configMap:
				    name: foobar-ns-app-01
				  name: config-volume
				- name: all-vault
				  projected:
				    sources:
				    - secret:
				        name: common-vault
			Template:	charts-integration-test/charts/app-02/templates/deployment.yaml
			DocumentIndex:	0
			Error:
				[2] :
				- configMap:
				    name: foobar-ns-app-02
				  name: config-volume
				- name: all-vault
				  projected:
				    sources:
				    - secret:
				        name: common-vault

 PASS  test integration Ingress	tests/ingress_test.yaml
 PASS  test integration service	tests/service_test.yaml

Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 97 passed, 98 total
Snapshot:    0 passed, 0 total
Time:        3.860298409s

```

@quintush it seems that the processing of yaml arrays has a fundumental flaw in logic. I wish I speaked go so I could inteligently look into it. Thanks for the effort.
