### ISSUE TITLE
[question] How can we assert prefixed labels?

### ISSUE THREAD

**Issue by edmeister** [quintush/helm-unittest#176]
Hi,

I was looking for a way to assert labels or annotations with the prefixed format as is currently recommended in Kubernetes. I tried multiple formats, but the YAML parser seems to be unable to handle this format in a path. 

What would you recommend here?

Example:
```
metadata:
  ...
  labels:
    app.kubernetes.io/name: example
```
