### ISSUE TITLE
[bug] - failedTemplate assertion is not working as expected

### ISSUE THREAD

**Issue by froy001** [quintush/helm-unittest#180]
I have a failedTempate assertion:
```yaml
    asserts:
      - failedTemplate:
          errorMessage: |
             global.application.commit and global.application.remoteOrigin must be given if rookout.enabled = true 
```

I get the following assertion failure:
```bash
		- asserts[0] `failedTemplate` fail
			Template:	charts-integration-test/charts/app-01/templates/deployment.yaml
			Template:	charts-integration-test/charts/app-02/templates/deployment.yaml
			DocumentIndex:	0
			Expected to equal:
				global.application.commit and global.application.remoteOrigin must be given if rookout.enabled = true
			Actual:
				global.application.commit and global.application.remoteOrigin must be given if rookout.enabled = true
```

As can be seen the expected and the actual values are exactly the same. This could be related to #174
