### ISSUE TITLE
Feature request: assert length

### ISSUE THREAD

**Issue by lokkersp** [quintush/helm-unittest#190]
There's part of the specs that required testing the count of objects inside a particular spec:
For example:
For ingress, there's a `spec.tls` section, and the count of defined hosts should match with `spec.rules`

It would be great to have something like the following:
```yaml
- it: length matches
  set:
    global.ingress.hosts:
       - prod.example.com
       - stage.example.com
  asserts:
     - lengthEqual:
         path: spec.tls # optional, conflicts with paths |
         paths: # optional, conflicts with path
           - spec.tls
           - spec.rules
         count: 2 # optional field if paths defined, but required if the path is used 
```
