### ISSUE TITLE
Feature: Add antonym and not to lengthEqual assertion

### ISSUE THREAD

**Issue by jzbruno** [quintush/helm-unittest#197]
Hello,

Thanks for adding the lengthEqual assertion in https://github.com/quintush/helm-unittest/issues/190. It looks like the antonym and not flags were not added like described in the documentation.

https://github.com/quintush/helm-unittest/blob/master/DOCUMENT.md#antonym-and-not

Please add them so we can do the following (using example from original feature request)

```yaml
- it: length matches
  set:
    global.ingress.hosts:
      - prod.example.com
      - stage.example.com
  asserts:
    - notLengthEqual:
        path: spec.tls
        count: 1
    - lengthEqual:
        path: spec.tls
        count: 1
      not: true
```
