### ISSUE TITLE
Feature: Add comparison with "any" value of a type

### ISSUE THREAD

**Issue by raysaik** [quintush/helm-unittest#198]
It would be good to have a "any" value comparison which we have in some of the Unit Test frameworks like XUnit. If I want to compare a value (lets say integer) set in the Values.yaml file and compare the output inside my template file to the expected value (e.g: <any> + 10). It should be something like the one below : 

**Values.yaml**
```
prometheus:
  prometheusRules:
    mythreshold: 5
```

**resource_test.yaml**
```
set:
   prometheus:
     prometheusRules:
            mythreshold: <any>
        

    asserts:
      - matchRegex:
          path: spec.SpecWherethisValueIsUsed
          pattern: "> <any>"
```

The problem with asserting hardcoded values in the test file is that someone can bypass the unit test failure by setting a hardcoded value in the template instead of reading it from Values.Yaml
