### ISSUE TITLE
[question] Testing NamedTemplates in my chart

### ISSUE THREAD

**Issue by grixxie** [quintush/helm-unittest#206]
Hey! First of all I just want to say I'm really impressed and enjoying this plugin :)

I'm fairly new to Helm in general. I've created a namedTemplate which is used in another yaml file in my chart using the _include_ keyword. 

I want to test the namedTemplate in isolation - is this possible?
I understand that a namedTemplate itself does not generate any output, and am also aware I could test this via the calling yaml; I'm mainly curious whether testing my namedTemplate by itself is possible.

A simple example below:

```yaml
# NamedTemplate
{{- define "testNamedTemplate" -}}
key: {{ .Values.testValue }}
{{- end -}}
```

```yaml
# my test
values: []
templates: []
tests:
  - it:
    template: 'testNamedTemplate.yaml'
    set:
      testValue: 'abc'
    asserts:
      - equal:
          path: key
          value: 'abc'
```

the above test will give me the error **"asserts[0] equal fail"**. 

My "fix" for this right now is to create a file in my chart called testNamedTemplate.include.yaml which is only used for tests, which looks like this:

```yaml
# testNamedTemplate.include.yaml
{{- include "testNamedTemplate" . -}}
```

Hopefully this makes sense and isn't too dumb of a question :)
