### ISSUE TITLE
Regression: matchRegex path name with dot not parsed correctly

### ISSUE THREAD

**Issue by krithika369** [quintush/helm-unittest#207]
Hello,

I have a secret resource as follows:

```yaml
apiVersion: v1
kind: Secret
metadata:
...
stringData:
  config.yaml: |
   ...
```

Until the official version `v0.2.11` of this plugin, I am able to write a test for it like so:

```yaml
      - matchRegex: # check database address
          path: stringData.[config.yaml]
          pattern: "Host: my-release-abc-postgresql.my-namespace.svc.cluster.local"
```

But, as of [the latest commit](https://github.com/quintush/helm-unittest/commit/254c582c18d52e07541dbe0185eb64befa20a822), I get the following error:

```
child name missing at position 11, following "stringData."
```

No issues if `config.yaml` is name `config-yaml`, for example.

It's not a problem for us as we can pin our plugin version to the official release version. But seeing that the test CI job is passing for the recent commits, I wanted to flag this.

Do let me know if you need any other info. Thanks!
