### ISSUE TITLE
Add support for setting Capabilities

### ISSUE THREAD

**Issue by stevelipinski** [quintush/helm-unittest#36]
helm allows for Capabilitiy detection, which is useful when using CRDs.

It would be nice if we could set the capabilities.  For this particular usecase of CRDs, setting .Capabilities.APIVersions.Has

**Comment by quintush** [comment]
Hello @stevelipinski,

Can you send me a sample project on your usage of CRDs.
Based on the original helm code, only setting Capabilities is probably not enough to have the plugin working for CRDs.

Greetings,
@quintush

**Comment by stevelipinski** [comment]
We have a CRD defined for a custom backup/restore component where we would define a manifest template like this:
```
{{- if and .Values.br.enabled (.Capabilities.APIVersions.Has "br.dev.local/v1") }}
---
apiVersion: "br.dev.local/v1"
kind: BrPolicy
metadata:
  name: {{ template "mychart.fullname" . }}-backuppolicy
  labels:
    {{- include "mychart.common_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "mychart.fullname" . }}
      type: myserver
  volumes:
  - datadir
{{- end }}
```

The above is truncated for simplicity, but we have many more items configured in this Backup/Restore Policy spies, and to be able to unittest them with varying Values inputs would be very useful.  

Currently I cannot unittest this because I have no way to influence the .Capabilities.APIVersions.Has.  
Ideally, we could somehow set some .Capabilities.

(Sorry, I can't contribute any code - don't know Go)
