### ISSUE TITLE
Test will always pass if the template YAML file is empty

### ISSUE THREAD

**Issue by quintush** [quintush/helm-unittest#41]
Problem
-----
If template YAML file is empty, test will alway pass.

How to reproduce
-----
Below passes as expected.

``` yaml
# templates/deployment.yaml
apiVersion: batch/v1beta1
kind: Deployment

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```
Below errors out with ``` - asserts[0] isKind fail ... Expected kind: Deployment ...Actual: null ```, as expected.

``` yaml
# templates/deployment.yaml
apiVersion: batch/v1beta1

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```
Below passes, but should actually fail:

``` yaml
# templates/deployment.yaml
##### Empty file #####

---
# tests/deployment_test.yaml
suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should pass
    values:
      - ../values.yaml
    asserts:
      - isKind:
          of: Deployment
```

Environment/Version
------
I am using the https://hub.docker.com/r/aneeshkj/helm-unittest docker image, which forks you from GitHub.
This issue is copied from https://github.com/lrills/helm-unittest/issues/107
