### ISSUE TITLE
Some errors on testing helm charts made for helm 2

### ISSUE THREAD

**Issue by gcavalcante8808** [quintush/helm-unittest#53]
Hi, I have a helm chart that was created for helm2 and the unittests were working with the `lrills/helm-unittest` plugin.

But when I try to use this version (Installed trought the `helm2 plugin install https://github.com/quintush/helm-unittest` command) some errors about template occurs.

Helm Version: 2.16.10

The tests:

```
suite: test autoscaling
templates:
  - horizontalpodautoscaler.yaml

tests:
  - it: should use GLOBAL scaling config when release autoscaling AND Global autoscaling are enabled
    set:
      infra:
        autoScaling:
          enabled: true
          minReplicas: 100
          maxReplicas: 500
      releases:
        - name: default
          environment: nimbus
          infra:
            autoScaling:
              enabled: true
              type: "hpa"
    asserts:
      - isKind:
          of: HorizontalPodAutoscaler
      - hasDocuments:
          count: 1
      - equal:
          path: spec.minReplicas
          value: 100
      - equal:
          path: spec.maxReplicas
          value: 500

  - it: should use release hpa config when Global autoscaling is disabled but release scaling is enabled.
    set:
      infra:
        autoScaling:
          enabled: false
          minReplicas: 5000
          maxReplicas: 7000
      releases:
        - name: default
          environment: nimbus
          infra:
            autoScaling:
              enabled: true
              minReplicas: 2
              maxReplicas: 2
    asserts:
      - isKind:
          of: HorizontalPodAutoscaler
      - hasDocuments:
          count: 1
      - equal:
          path: spec.minReplicas
          value: 2
      - equal:
          path: spec.maxReplicas
          value: 2

  - it: should'n't use any autoscaling config when release autoscaling is disabled
    set:
      infra:
        autoScaling:
          enabled: true
          minReplicas: 5000
          maxReplicas: 7000
      releases:
        - name: default
          environment: nimbus
          infra:
            autoScaling:
              enabled: false
              minReplicas: 2
              maxReplicas: 2
    asserts:
      - hasDocuments:
          count: 0
```
Errors:
```
 	- should use GLOBAL scaling config when release autoscaling AND Global autoscaling are enabled
		- asserts[0] `isKind` fail
			Error:
				assertion.template must be given if testsuite.templates is empty
		- asserts[1] `hasDocuments` fail
			Error:
				assertion.template must be given if testsuite.templates is empty
		- asserts[2] `equal` fail
			Error:
				assertion.template must be given if testsuite.templates is empty
		- asserts[3] `equal` fail
			Error:
				assertion.template must be given if testsuite.templates is empty
```

Can u provide some method to debug these problems?

Thanks for the awesome work!
