### ISSUE TITLE
`failedTemplate` error not exists or not selected in test suite

### ISSUE THREAD

**Issue by AmitBenAmi** [quintush/helm-unittest#70]
Hi

I have a test which I'm trying to test that it is failing with

This is my `_helpers.tpl`:
```
{{- define "my-chart.checkNameOverrideLength" -}}
{{- if .Values.nameOverride -}}
{{- if gt (len .Values.nameOverride) 54 -}}
{{- fail "nameOverride cannot be longer than 54 characters" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "my-chart.name" -}}
{{- include "web-api.checkNameOverrideLength" . -}}
{{- .Values.nameOverride -}}
{{- end -}}
```

This is my test:
```
suite: test
templates:
  - deployment.yaml
tests:
  - it: should fail since the nameOverride is too long
    values:
      - ../../values.yaml
    set:
      nameOverride: too-long-of-a-name-override-that-should-fail-the-template-immediately
    asserts:
      - failedTemplate:
          errorMessage: nameOverride cannot be longer than 54 characters
```

As you can see, all I try to check is that I get the error from the template, but I keep getting this error:
```
 FAIL  test     helm-unittest/common/values_test.yaml
        - should fail since the nameOverride is too long

                - asserts[0] `failedTemplate` fail

                        Error:
                                template "my-chart/templates/deployment.yaml" not exists or not selected in test suite


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        18.780023ms

Error: plugin "unittest" exited with error
```

Any reason why it could happen and how can I resolve it?
Thanks
