### ISSUE TITLE
Strange behavior when using "toYaml" function

### ISSUE THREAD

**Issue by dntosas** [quintush/helm-unittest#86]
### Description
Plugin seems not to match correctly output from rendered template and fails

So, we have the following into `deployment.yaml` file:
```go
[...]
          {{- if $c.livenessProbe }}
          livenessProbe:
            {{- toYaml $c.livenessProbe | nindent 12 }}
          {{- end }}
          {{- with $c.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
[...]          
```
As you can see, we try different approaches with `if` and `with` to test different scenarios ^^

When running `helm template ...` we got the following output which is correct:
```yaml
[...]
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
[...]
```

Now, we have also set a test like this:
```yaml
      - equal:
          path: spec.template.spec.containers[0].livenessProbe
          value:
            httpGet:
              path: /
              port: http
      - equal:
          path: spec.template.spec.containers[0].readinessProbe
          value:
            httpGet:
              path: /
              port: http
```

Tests fails with the following output, complaining that value of above is `null`:
```yaml
               - asserts[10] `equal` fail
                        Template:       templates/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.containers[0].livenessProbe
                        Expected to equal:
                                httpGet:
                                  path: /
                                  port: http
                        Actual:
                                null

                - asserts[11] `equal` fail
                        Template:       templates/deployment.yaml
                        DocumentIndex:  0
                        Path:   spec.template.spec.containers[0].readinessProbe
                        Expected to equal:
                                httpGet:
                                  path: /
                                  port: http
                        Actual:
                                null
```

### Expected Behavior
We expect test suite to succeed ^^ Are we missing something or any clues? We migrated from `lrills/helm-unittest` into your project to utilize helm3 and thought to ask if something had changed in behavior

PS: Thanks for you nice work :smiley:

**Comment by quintush** [comment]
Hello @dntosas,

With the migrations to helm3 i made the option to assert multiple templates together, which has a great benefit for recurring patterns.

The downside is that the errorhandling is still lacking. I'm working on it to improve the errorhandling.

For your specific case, can you send me the complete deployment.yaml? The fact that it can't find the path seems that something is missing before.

Greetings@quintush

**Comment by dntosas** [comment]
Sure @quintush, here we are:
```yaml
apiVersion: apps/v1
kind: Deployment
{{ template "lib-metadata.metadata" . }}
  name: {{ template "lib-metadata.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lib-metadata.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "lib-metadata.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.esIndexName }}
        es_index: {{ .Values.esIndexName }}
        {{- end }}
      annotations:
        kubernetes.io/change-cause: {{ .Values.changeCause }}
        {{- if .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.monitoring.path }}"
        prometheus.io/port: "{{ .Values.monitoring.port }}"
        {{- end }}
        {{- if .Values.iamRole.enabled }}
        iam.amazonaws.com/role: "{{ .Values.iamRole.name }}"
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      containers:
        {{- range $c := .Values.containers }}
        - name: {{ $c.name | squote }}
          image: "test"
          imagePullPolicy: "test"
          {{- if $c.command }}
          command: {{ printf (mustToJson .command) }}
          {{- end }}
          {{- if $c.extraArgs }}
          args: {{ printf (mustToJson .extraArgs) }}
          {{- end }}
          ports:
            {{- range $.Values.service.ports }}
            - name: {{ .name | default (printf "%s-%d" (.protocol | default "HTTP" | lower) (int64 .port)) | quote }}
              containerPort: {{ .port }}
              protocol: "TCP"
            {{- end }}
          env:
          {{- range $key, $value := $c.env }}
          - name: {{ $key }}
            value: {{ $value | squote }}
          {{- end }}
          {{- if $.Values.tracing.enabled }}
          {{- range $key, $value := $.Values.tracing.env }}
          - name: {{ $key }}
            value: {{ $value | squote }}
          {{- end }}
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- end }}
          {{- with $c.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $c.livenessProbe }}
          livenessProbe:
            {{- toYaml $c.livenessProbe | nindent 12 }}
          {{- end }}
          {{- with $c.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $c.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.configMaps.enabled }}
          volumeMounts:
          {{- range $r := $.Values.configMaps.cms }}
          - name: {{ $r.name }}
            mountPath: {{ printf "%s/%s" $r.mountPath $r.fileName | squote }}
            subPath: {{ $r.fileName | squote }}
            readOnly: true
          {{- end }}
          {{- end }}
          {{- if $.Values.secrets.enabled }}
          volumeMounts:
          - name: secrets
            mountPath: {{ $.Values.secrets.mountPath | squote }}
            readOnly: true
          {{- end }}
        {{- end }}
      serviceAccountName: {{ include "lib-metadata.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- if .Values.configMaps.enabled }}
      volumes:
      {{- range .Values.configMaps.cms }}
      - name: {{ .name }}
        configMap:
          name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .Values.secrets.enabled }}
      volumes:
      - name: secrets
        secret:
          secretName: {{ template "lib-metadata.fullname" . }}
          items:
          {{- range $key, $value := .Values.secrets.items }}
          - key: {{ $key }}
            path: {{ $key }}
          {{- end }}
          {{- range $key, $value := .Values.secrets.files }}
          - key: {{ $key }}
            path: {{ $key }}
          {{- end }}
      {{- end }}
```

>The fact that it can't find the path seems that something is missing before.
I will also try to isolate the case ^^ I tried removing everything else (templates, metadata, labels) and just keep this single block but with same behavior, maybe I missed something so I will retry it.

**Comment by dntosas** [comment]
UPDATE:

When I explicitly set values in test, it succeed. When it takes values from default `values.yaml` inside the chart, it fails as described:
```yaml
    set:
      global.labels.owner: platform
      containers:
        - name: pame
          livenessProbe:
            httpGet:
              path: "/"
              port: "http"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
```     
This suceeds ^^
